#pragma once
// Arduino replacement for esp-dl Kconfig PIX_CVT_* options (all default y).
#define CONFIG_PIX_CVT_RGB565_TO_RGB565_SUPPORT 1
#define CONFIG_PIX_CVT_RGB565_TO_RGB888_SUPPORT 1
#define CONFIG_PIX_CVT_RGB565_TO_GRAY_SUPPORT 1
#define CONFIG_PIX_CVT_RGB565_TO_HSV_SUPPORT 1
#define CONFIG_PIX_CVT_RGB888_TO_RGB888_SUPPORT 1
#define CONFIG_PIX_CVT_RGB888_TO_RGB565_SUPPORT 1
#define CONFIG_PIX_CVT_RGB888_TO_GRAY_SUPPORT 1
#define CONFIG_PIX_CVT_RGB888_TO_HSV_SUPPORT 1
#define CONFIG_PIX_CVT_GRAY_TO_GRAY_SUPPORT 1
#define CONFIG_PIX_CVT_HSV_TO_HSV_MASK_SUPPORT 1
#define CONFIG_PIX_CVT_YUV_TO_RGB888_SUPPORT 1
#define CONFIG_PIX_CVT_YUV_TO_RGB565_SUPPORT 1
#define CONFIG_PIX_CVT_YUV_TO_GRAY_SUPPORT 1
#define CONFIG_PIX_CVT_YUV_TO_HSV_SUPPORT 1
#define CONFIG_PIX_CVT_YUV_TO_YUV_SUPPORT 1
